### ISSUE TITLE
Why is open-source forbidden?

### ISSUE THREAD

**Issue by MrCsabaToth** [VeryGoodOpenSource/very_good_dictionaries#7]
According to Gemini Advanced:

> The proper spelling is "**open source**" as two words without a dash.
> 
> However, when used as an adjective before a noun, it is hyphenated: "**open-source software**".
> 
> Here are some examples:
>
> * **Noun**: "This project embraces the principles of open source."
> * **Adjective**: "We are developing an open-source application."

**Comment by tomarra** [comment]
Hi @MrCsabaToth 👋 thanks for opening this issue. Overall the dictionaries defined here are just the style that Very Good Ventures has chosen to implement in order to keep things consistent in all of our work. Given that, we're not going to be making this change as this is something we have already aligned on internally. You're welcome to fork this repo and make changes to your own copy if that would help out though.

Closing as won't fix.
